### ISSUE TITLE
Cannot implement a validate-all handler

### ISSUE THREAD

**Issue by aieri** [CygnusNetworks/pyocfagent#2]
Due to the python limitations in regard to function names, we cannot write a `handle_validate-all` function. Pacemaker will however pass `validate-all` as an argument, therefore an internal translation or special handling of such argument is required.

**Comment by cygnusb** [comment]
I would suggest simply mangling the given name from validate-all to validate_all by replacing all "-" chars to "_" prior to parsing. This should do the job for this special case.

**Comment by cygnusb** [comment]
Feel free to implement this and submit a pull request. I have currently no time to implement and test this.

**Comment by cygnusb** [comment]
Please create a Pull request to get this included

**Comment by cygnusb** [comment]
Already merged
